### ISSUE TITLE
Client.js?

### ISSUE THREAD

**Issue by TehcJS** [LegusX/xhordesmapi#1]
What does everything in client.js mean? I'm happy to help with the xhordesmapi, and in fact I'd like to see it grow. It has much opportunity. I don't like to see it get wasted like this. If you see this, please DM me on Discord ASAP. Tehc#6346

**Comment by LegusX** [comment]
Client.js is the actual hordes.io game code.
In the original xhordes, we actually directly modified this file and then replaced it in the player client to "mod" the game.
However the plan for xmapi is to actually automate the modifying process so that the api can automatically be ported to each new version of the game. (Or at least that's the hope)

You can check out this [readme](https://github.com/LegusX/xhordesmapi/blob/master/autoupdater/autoupdater.md) for more information on how I plan to do that

**Comment by TehcJS** [comment]
Thanks for the information!
